scenarios["badoon"] = {
    name = "Brotherhood of Badoon",
    tileImageUrl = "https://steamusercontent-a.akamaihd.net/ugc/1833525990616300296/C9276570D20792F346FDE1CC56A8C6AF0DF576F3/",
    villains = {
        drang = {
            name = "Drang",
            hpCounter = {
                imageUrl = "https://steamusercontent-a.akamaihd.net/ugc/1833525990616300296/C9276570D20792F346FDE1CC56A8C6AF0DF576F3/"
            },
            stages = {
                stage1 = {
                    cardId = "16058",
                    hitPointsPerPlayer = 13
                },
                stage2 = {
                    cardId = "16059",
                    hitPointsPerPlayer = 14
                },
                stage3 = {
                    cardId = "16060",
                    hitPointsPerPlayer = 18
                }
            }
        }
    },
    schemes = {
        main = {
            stages = {
                stage1 = {
                    cardId = "16061",
                    startingThreatPerPlayer = 2,
                    targetThreatPerPlayer = 8,
                    accelerationPerPlayer = 2
                },
                stage2 = {
                    cardId = "16062",
                    startingThreatPerPlayer = 4,
                    targetThreatPerPlayer = 8,
                    accelerationPerPlayer = 2
                }
            }
        }
    },
    cards = {
        milano = {
            cardId = "16142",
            position = {0, 1.00, 1.25},
            scale = Vector(Global.getVar("CARD_SCALE_PLAYER"))
        }
    },
    decks = {
        encounterDeck = {
            name = "Drang's Encounter Deck",
            cards = {
                ["16063"] = 1,
                ["16064"] = 1,
                ["16065"] = 2,
                ["16066"] = 1,
                ["16067"] = 1,
                ["16068"] = 1,
                ["16069"] = 1
            }
        }
    },
    modularSets = {
        shipCommand = "required",
        bandOfBadoon = "recommended"
    }
}

function setUpSchemeStage_badoon_main(params)
    local stage = params.stage
    local stageNumber = string.sub(stage.key, -1)
    local badoonShipCardId = "16063"

    if (stageNumber == "1") then
        Global.call("moveCardFromEncounterDeckById", {
            cardId = badoonShipCardId,
            searchInDiscard = true,
            zoneIndex = "environment"
        })
    end
end
