scenarios["getaway"] = {
    name = "The Getaway",
    fullyScripted = true,
    tileImageUrl = "https://steamusercontent-a.akamaihd.net/ugc/2035118913124026079/1346FDBB47BCA704CFA9E914755A9AAF6B1CD5A3/",
    villains = {},
    schemes = {
        main = {
            stages = {
                stage1 = {
                    cardId = "60128",
                    startingThreatPerPlayer = 2,
                    accelerationPerPlayer = 2,
                    targetThreatPerPlayer = 9
                }
            }
        }
    },
    decks = {
        encounterDeck = {
            name = "The Getaway Encounter Deck",
            cards = {
                ["60129"] = 1,
                ["60130"] = 1,
                ["60131"] = 1,
                ["60132"] = 2,
                ["60133"] = 2
            }
        }
    },
    modularSets = {
        cops = "recommended",
        drive = "recommended"
    }
}

function getEncounterSetControlPanel_getaway()
    return fearNoEvilGetEncounterSetPanel()
end

function prepareScenario_getaway()
    fearNoEvilPrepareScenario()
end

function setUpSchemeStage_getaway_main(params)
    local outFrontCardId = "60129"
    Global.call("moveCardFromEncounterDeckById", {
        cardId = outFrontCardId,
        searchInDiscard = true,
        zoneIndex = "attachment"
    })
end

function setUpVillainStage_artMuseumHeist(params)
    fearNoEvilSetupVillainStage(params)
end
