scenarios["hela"] = {
    name = "Hela",
    tileImageUrl = "https://steamusercontent-a.akamaihd.net/ugc/1849305905150128726/5561A2846A40991CD9F774C0CA75572DC3A7C096/",
    villains = {
        hela = {
            name = "Hela",
            locked = false,
            hpCounter = {
                imageUrl = "https://steamusercontent-a.akamaihd.net/ugc/1849305905150128726/5561A2846A40991CD9F774C0CA75572DC3A7C096/"
            },
            stages = {
                stageA = {
                    cardId = "21136",
                    hitPointsPerPlayer = 8
                },
                stageB = {
                    cardId = "21137",
                    hitPointsPerPlayer = 9
                }
            }
        }
    },
    schemes = {
        main = {
            stages = {
                stage1 = {
                    cardId = "21138",
                    startingThreatPerPlayer = 1,
                    targetThreatPerPlayer = 18
                }
            }
        }
    },
    decks = {
        encounterDeck = {
            name = "Hela's Encounter Deck",
            cards = {
                ["21139"] = 1,
                ["21140"] = 1,
                ["21143"] = 1,
                ["21146"] = 1,
                ["21147"] = 1,
                ["21148"] = 1,
                ["21149"] = 2,
                ["21150"] = 2,
                ["21151"] = 2
            }
        },
        setAside = {
            name = "Set Aside Cards",
            position = {-15.25, 1.25, 30.25},
            scale = Vector(Global.getVar("CARD_SCALE_ENCOUNTER")),
            cards = {
                ["21141"] = 1,
                ["21142"] = 1,
                ["21144"] = 1,
                ["21145"] = 1
            }
        }
    },
    modularSets = {
        legionsOfHel = "recommended",
        frostGiants = "recommended"
    }
}

function setUpSchemeStage_hela_main(params)
    local stage = params.stage
    local stageNumber = string.sub(stage.key, -1)
    local odinCardId = "21139"
    local gnipahellirCardId = "21140"
    local garmCardId = "21143"

    if (stageNumber == "1") then
        Global.call("moveCardFromEncounterDeckById", {
            cardId = odinCardId,
            searchInDiscard = true,
            destinationPosition = {17.75, 1.00, 22.75},
            scale = Vector(Global.getVar("CARD_SCALE_PLAYER"))
        })

        Global.call("moveCardFromEncounterDeckById", {
            cardId = gnipahellirCardId,
            searchInDiscard = true,
            zoneIndex = "sideScheme"
        })

        Global.call("moveCardFromEncounterDeckById", {
            cardId = garmCardId,
            searchInDiscard = true,
            destinationPosition = {0, 1.00, 1.25}
        })
    end
end
