scenarios["kingpin"] = {
    name = "Kingpin",
    fullyScripted = true,
    tileImageUrl = cdnUrl .. "/selectors/scenarios/selector-kingpin.png",
    villains = {
        kingpin = {
            name = "Kingpin",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-kingpin.png"
            },
            stages = {
                stage1 = {
                    cardId = "60159",
                    hitPointsPerPlayer = 14,
                    locked = false
                },
                stage2 = {
                    cardId = "60160",
                    hitPointsPerPlayer = 15,
                    locked = false
                }
            }
        }
    },
    schemes = {
        main = {
            stages = {
                stage1 = {
                    cardId = "60161",
                    startingThreat = 0,
                    startingThreatPerPlayer = 3,
                    targetThreatPerPlayer = 11
                },
                stage2 = {
                    cardId = "60162",
                    startingThreat = 0,
                    targetThreatPerPlayer = 7,
                    flavorText = "\"You so-called heroes have been a thorn in all of our sides for far too long. Together we will destroy you and rule this city!\" --Kingpin"
                }
            }
        }
    },
    decks = {
        encounterDeck = {
            name = "Kingpin's Encounter Deck",
            cards = {
                ["60163"] = 1,
                ["60164"] = 1,
                ["60165"] = 1,
                ["60166"] = 1,
                ["60167"] = 1,
                ["60168"] = 1,
                ["60169"] = 1,
                ["60170"] = 1,
                ["60171"] = 1,
                ["60172"] = 1,
                ["60173"] = 1,
                ["60174"] = 1,
                ["60175"] = 3,
                ["60176"] = 3
            }
        }
    },
    modularSets = {
        tombstone = "recommended",
        tracksuitMafia = "recommended"
    }
}

function setUpSchemeStage_kingpin_main(params)
    local stage = params.stage
    local stageNumber = string.sub(stage.key, -1)
    local mode = getMode()
    local publicSupportCardId = "60163"
    local organizedCrimeCardId = "60174"

    if (stageNumber == "1") then
        kingpinPlaceAllNemesisDecks()
        Global.call("displayMessage", {
            message = "Reveal each hero's nemesis minion. If that minion shares a title with a character in play, remove that minion from the game and find an reveal an Underling minion instead.",
            messageType = Global.getVar("MESSAGE_TYPE_INSTRUCTION")
        })

        Global.call("moveCardFromEncounterDeckById", {
            cardId = publicSupportCardId,
            searchInDiscard = true,
            zoneIndex = "environment",
            settings = {
                hideWhenFaceDown = false
            }
        })
    end

    if (stageNumber == "2") then
        Global.call("displayMessage", {
            message = "Find and reveal each hero's nemesis minion. Each player whose nemesis minion did not enter play in this way should find an Underling minion and reveal it instead.",
            messageType = Global.getVar("MESSAGE_TYPE_INSTRUCTION")
        })

        if (mode == "expert") then
            Global.call("moveCardFromEncounterDeckById", {
                cardId = organizedCrimeCardId,
                searchInDiscard = true,
                zoneIndex = "sideScheme"
            })
        end
    end
end

function kingpinPlaceAllNemesisDecks()
    local heroManager = getObjectFromGUID(Global.getVar("GUID_HERO_MANAGER"))
    local players = heroManager.call("getPlayersInPlayerOrder")

    for _, player in ipairs(players) do
        local playmat = heroManager.call("getPlaymat", {
            playerColor = player.playerColor,
            test = "blah"
        })
        local nemesisPosition = Vector(playmat.call("getEncounterCardPosition"))

        spawnNemesis({
            playerColor = player.playerColor,
            position = nemesisPosition
        })
    end
end

function fearNoEvilGetEncounterSetPanel()
    local underlings = {{
        key = "bullseye",
        name = "Bullseye"
    }, {
        key = "electro",
        name = "Electro"
    }, {
        key = "hammerhead",
        name = "Hammerhead",
        label = "Hammer-\nhead"
    }, {
        key = "purpleMan",
        name = "Purple Man",
        fileName = "purple-man",
        label = "Purple\nMan"
    }, {
        key = "typhoidMary",
        name = "Typhoid Mary",
        fileName = "typhoid-mary",
        label = "Typhoid\nMary"
    }}

    local guid = self.getGUID()
    local underlingButtons = {}
    local selectedUnderlingButtonId = selectedScenario.underlingButtonId or "random"
    local randomButtonImageUrl =
        "https://steamusercontent-a.akamaihd.net/ugc/12635327849228453947/CB7134374683D9348843072934D55AF278B01109/"

    for _, underling in pairs(underlings) do
        local isSelected = underling.key == selectedUnderlingButtonId
        local underlingLabel = underling.label or underling.Label or underling.name

        table.insert(underlingButtons, {
            tag = "Panel",
            attributes = {
                preferredHeight = "85",
                preferredWidth = "170",
                id = "underlingHighlight-" .. underling.key,
                color = isSelected and "rgba(1,1,0,1)" or "rgba(0,0,0,0)"
            },
            children = {{
                tag = "Button",
                attributes = {
                    id = underling.key,
                    onClick = guid .. "/fearNoEvilUnderlingButtonClicked",
                    preferredHeight = "85",
                    preferredWidth = "170",
                    color = "rgba(0,0,0,0)",
                    colors = "rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)"
                },
                children = {{
                    tag = "Image",
                    attributes = {
                        image = cdnUrl .. "/selectors/scenarios/selector-" .. (underling.fileName or underling.key) ..
                            ".png",
                        height = "81",
                        width = "166",
                        preserveAspect = "false",
                        rectAlignment = "MiddleCenter"
                    }
                }, {
                    tag = "Text",
                    value = underlingLabel,
                    attributes = {
                        alignment = "MiddleCenter",
                        rectAlignment = "MiddleCenter",
                        offsetXY = "35 7",
                        fontSize = "18",
                        color = "rgba(0,0,0,1)",
                        raycastTarget = "false"
                    }
                }}
            }}
        })
    end

    local randomSelected = selectedUnderlingButtonId == "random"
    table.insert(underlingButtons, {
        tag = "Panel",
        attributes = {
            preferredHeight = "85",
            preferredWidth = "85",
            id = "underlingHighlight-random",
            color = randomSelected and "rgba(1,1,0,1)" or "rgba(0,0,0,0)"
        },
        children = {{
            tag = "Button",
            attributes = {
                id = "random",
                onClick = guid .. "/fearNoEvilUnderlingButtonClicked",
                preferredHeight = "85",
                preferredWidth = "85",
                color = "rgba(0,0,0,0)",
                colors = "rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)"
            },
            children = {{
                tag = "Image",
                attributes = {
                    image = randomButtonImageUrl,
                    height = "81",
                    width = "81",
                    preserveAspect = "false",
                    rectAlignment = "MiddleCenter"
                }
            }}
        }}
    })

    local encounterSetControlPanel = {
        tag = "Panel",
        attributes = {
            preferredHeight = "125",
            flexibleHeight = "0",
            width = "955"
        },
        children = {{
            tag = "VerticalLayout",
            attributes = {
                rectAlignment = "UpperLeft",
                childAlignment = "UpperLeft",
                childForceExpandHeight = "false",
                spacing = "10",
                contentSizeFitter = "vertical"
            },
            children = {{
                tag = "Text",
                value = "Select an underling villain.",
                attributes = {
                    rectAlignment = "UpperLeft",
                    alignment = "UpperLeft",
                    color = "rgba(1,1,1,1)"
                }
            }, {
                tag = "HorizontalLayout",
                attributes = {
                    childAlignment = "MiddleCenter",
                    childForceExpandHeight = "false",
                    childForceExpandWidth = "false",
                    preferredHeight = "85",
                    width = "955",
                    spacing = "4",
                    contentSizeFitter = "vertical"
                },
                children = underlingButtons
            }}
        }}
    }

    return encounterSetControlPanel
end

function fearNoEvilPrepareScenario()
    local selectedVillainKey = selectedScenario.underlingKey or "random"
    local selectedVillain = fearNoEvilGetUnderling(selectedVillainKey)
    local villainKey = selectedVillain.key
    local encounterDeck = currentScenario.decks.encounterDeck
    local villainEncounterCards = selectedVillain.encounterCards

    currentScenario.villains[villainKey] = selectedVillain

    for cardId, count in pairs(villainEncounterCards) do
        encounterDeck.cards[cardId] = count
    end

    if (selectedVillainKey == "typhoidMary") then
        local coinFlip = math.random(2)

        if (coinFlip == 2) then
            currentScenario.villains.typhoidMary.stages.stageA.flipCard = true
            currentScenario.villains.typhoidMary.stages.stageB.flipCard = true
        end
    end
end

function fearNoEvilSetupVillainStage(params)
    local villainKey = params.villainKey
    local stage = params.stage
    local stageNumber = string.sub(stage.key, -1)
    local mode = getMode()

    if (villainKey == "bullseye") then
        local adamantiumSpineCardId = "60068"
        local derangedBloodlustCardId = "60073"

        if (stageNumber == "1") then
            local encounterDeck = Global.call("getEncounterDeck")
            local encounterCards = encounterDeck.getObjects()

            for _, card in pairs(encounterCards) do
                local cardData = Global.call("getCardData", {
                    card = card
                })
                local cardId = cardData.code

                if (cardId == adamantiumSpineCardId) then
                    card = encounterDeck.takeObject({
                        guid = card.guid
                    })
                    if (card) then
                        card.destruct()
                    end
                    break
                end
            end
        end
        if (stageNumber == "2") then
            if (mode == "standard") then
                Global.call("spawnCardAndMoveFromEncounterDeckById", {
                    cardId = adamantiumSpineCardId,
                    zoneIndex = "attachment",
                    settings = {
                        hideWhenFaceDown = false
                    }
                })
            else
                Global.call("moveCardFromEncounterDeckById", {
                    cardId = adamantiumSpineCardId,
                    searchInDiscard = true,
                    zoneIndex = "attachment",
                    settings = {
                        hideWhenFaceDown = false
                    }
                })
            end
        end
        if (stageNumber == "3") then
            Global.call("moveCardFromEncounterDeckById", {
                cardId = derangedBloodlustCardId,
                searchInDiscard = true,
                zoneIndex = "sideScheme"
            })
        end
    end

    if (villainKey == "electro") then
        local electricChargeCardId = "60079"

        function setupElectricShock()
            Global.call("moveCardFromEncounterDeckById", {
                cardId = electricChargeCardId,
                searchInDiscard = true,
                zoneIndex = "attachment"
            })
        end

        function addShockCountersToElectricCharge(multiplier)
            local electricChargeCard = Global.call("findCard", {
                cardId = electricChargeCardId
            })
            local electricChargeCounter = Global.call("getCounterFromCard", {
                card = electricChargeCard,
                counterClass = "configured"
            })
            local heroCount = getHeroCount()

            electricChargeCounter.call("adjustValue", {
                adjustment = heroCount * multiplier
            })
        end

        if (stageNumber == "1") then
            setupElectricShock()
        end

        if (stageNumber == "2") then
            if (mode == "expert") then
                setupElectricShock()
            else
                addShockCountersToElectricCharge(2)
            end
        end

        if (stageNumber == "3") then
            addShockCountersToElectricCharge(3)
        end
    end

    if (villainKey == "typhoidMary") then
        local villainCard = Global.call("findCard", {
            cardId = stage.cardId
        })

        local villainIsFaceUp = Global.call("isFaceUp", {
            object = villainCard,
            ignoreToggles = true
        })

        fearNoEvilApplyTyphoidMaryExpertEffects(mode, villainIsFaceUp)
    end
end

function fearNoEvilGetUnderling(key)
    local underlings = {
        bullseye = {
            key = "bullseye",
            name = "Bullseye",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-bullseye.png"
            },
            stages = {
                stage1 = {
                    key = "stage1",
                    cardId = "60065",
                    hitPointsPerPlayer = 14
                },
                stage2 = {
                    key = "stage2",
                    cardId = "60066",
                    hitPointsPerPlayer = 16
                },
                stage3 = {
                    key = "stage3",
                    cardId = "60067",
                    hitPointsPerPlayer = 18
                }
            },
            encounterCards = {
                ["60068"] = 1,
                ["60069"] = 1,
                ["60070"] = 1,
                ["60071"] = 3,
                ["60072"] = 1,
                ["60073"] = 1,
                ["60074"] = 1,
                ["60075"] = 2
            }
        },
        electro = {
            key = "electro",
            name = "Electro",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-electro.png"
            },
            stages = {
                stage1 = {
                    key = "stage1",
                    cardId = "60076",
                    hitPointsPerPlayer = 15
                },
                stage2 = {
                    key = "stage2",
                    cardId = "60077",
                    hitPointsPerPlayer = 17
                },
                stage3 = {
                    key = "stage3",
                    cardId = "60078",
                    hitPointsPerPlayer = 20
                }
            },
            encounterCards = {
                ["60079"] = 1,
                ["60080"] = 1,
                ["60081"] = 1,
                ["60082"] = 2,
                ["60083"] = 2,
                ["60084"] = 2,
                ["60085"] = 2
            }
        },
        hammerhead = {
            key = "hammerhead",
            name = "Hammerhead",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-hammerhead.png"
            },
            stages = {
                stage1 = {
                    key = "stage1",
                    cardId = "60086",
                    hitPointsPerPlayer = 14
                },
                stage2 = {
                    key = "stage2",
                    cardId = "60087",
                    hitPointsPerPlayer = 15
                },
                stage3 = {
                    key = "stage3",
                    cardId = "60088",
                    hitPointsPerPlayer = 16
                }
            },
            encounterCards = {
                ["60089"] = 1,
                ["60090"] = 1,
                ["60091"] = 1,
                ["60092"] = 2,
                ["60093"] = 2,
                ["60094"] = 1,
                ["60095"] = 1,
                ["60096"] = 2
            }
        },
        purpleMan = {
            key = "purpleMan",
            name = "Purple Man",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-purple-man.png"
            },
            stages = {
                stage1 = {
                    key = "stage1",
                    cardId = "60097",
                    hitPointsPerPlayer = 13
                },
                stage2 = {
                    key = "stage2",
                    cardId = "60098",
                    hitPointsPerPlayer = 15
                },
                stage3 = {
                    key = "stage3",
                    cardId = "60099",
                    hitPointsPerPlayer = 17
                }
            },
            encounterCards = {
                ["60100"] = 1,
                ["60101"] = 2,
                ["60102"] = 1,
                ["60103"] = 1,
                ["60104"] = 1,
                ["60105"] = 1,
                ["60106"] = 1,
                ["60107"] = 1,
                ["60108"] = 1,
                ["60109"] = 2
            }
        },
        typhoidMary = {
            key = "typhoidMary",
            name = "Typhoid Mary",
            hpCounter = {
                imageUrl = cdnUrl .. "/selectors/scenarios/selector-typhoid-mary.png",
                primaryButtonLabel = "RESET",
                primaryButtonClickFunction = "fearNoEvilResetTyphoidMary"
            },
            stages = {
                stageA = {
                    key = "stageA",
                    cardId = "60110",
                    hitPointsPerPlayer = 10,
                    locked = false,
                    showAdvanceButton = true
                },
                stageB = {
                    key = "stageB",
                    cardId = "60111",
                    hitPointsPerPlayer = 13,
                    locked = false,
                    showAdvanceButton = true
                }
            },
            encounterCards = {
                ["60112"] = 1,
                ["60113"] = 1,
                ["60114"] = 1,
                ["60115"] = 2,
                ["60116"] = 1,
                ["60117"] = 1,
                ["60118"] = 2,
                ["60119"] = 1,
                ["60120"] = 3
            }
        }
    }

    if (key == "random") then
        local underlingKeys = {}

        for key, underling in pairs(underlings) do
            table.insert(underlingKeys, key)
        end

        underlingKeys = Global.call("shuffleTable", {
            table = underlingKeys
        })

        return underlings[underlingKeys[1]]
    end

    return underlings[key]
end

function fearNoEvilUnderlingButtonClicked(player, value, id)
    local underlingButtonIds = {"bullseye", "electro", "hammerhead", "purpleMan", "typhoidMary", "random"}

    for _, underlingButtonId in ipairs(underlingButtonIds) do
        local isSelected = underlingButtonId == id
        Global.UI.setAttribute("underlingHighlight-" .. underlingButtonId, "color",
            isSelected and "rgba(1,1,0,1)" or "rgba(0,0,0,0)")
    end

    selectedScenario.underlingButtonId = id
    selectedScenario.underlingKey = id
end

function fearNoEvilResetTyphoidMary()
    local villainHpCounter = getObjectFromGUID(currentScenario.villains.typhoidMary.hpCounter.guid)
    local mode = currentScenario.mode
    local stage = mode == "standard" and currentScenario.villains.typhoidMary.stages.stageA or
                      currentScenario.villains.typhoidMary.stages.stageB
    local heroCount = getHeroCount()

    villainHpCounter.call("setValue", {
        value = stage.hitPointsPerPlayer * heroCount
    })

    local disturbedPsycheCardId = "60112"
    local disturbedPsycheCard = Global.call("findCard", {
        cardId = disturbedPsycheCardId
    })
    local disturbedPsycheCounter = Global.call("getCounterFromCard", {
        card = disturbedPsycheCard,
        counterClass = "configured"
    })

    disturbedPsycheCounter.call("adjustValue", {
        adjustment = 1
    })

    local currentDisturbedPsycheDamage = disturbedPsycheCounter.call("getValue")

    if currentDisturbedPsycheDamage >= 3 then
        Global.call("displayMessage", {
            message = "Typhoid Mary has been defeated. The Heroes win!",
            messageType = Global.getVar("MESSAGE_TYPE_ALERT")
        })
    end

    local villainCard = Global.call("findCard", {
        cardId = stage.cardId
    })

    local villainIsFaceUp = Global.call("isFaceUp", {
        object = villainCard,
        ignoreToggles = true
    })

    villainCard.flip()

    villainIsFaceUp = not villainIsFaceUp
    fearNoEvilApplyTyphoidMaryExpertEffects(mode, villainIsFaceUp)
end

function fearNoEvilApplyTyphoidMaryExpertEffects(mode, villainIsFaceUp)
    if (mode == "expert") then
        if (villainIsFaceUp) then
            Global.call("addStatusToVillain", {
                villain = currentScenario.villains.typhoidMary,
                statusType = "tough"
            })
        else
            Global.call("displayMessage", {
                message = "Bloody Mary deals 1 damage to each identity.",
                messageType = Global.getVar("MESSAGE_TYPE_INSTRUCTION")
            })
        end
    end
end
