scenarios["mojo"] =
{
    name="Mojo",
    fullyScripted = true,
    tileImageUrl="https://steamusercontent-a.akamaihd.net/ugc/2292958473528765513/0B1849865D7DC2D609879B9D02E723B0DDE60D7F/",
    preselectModularEncounterSets = false,
    villains={
        mojo={
            name="Mojo",
            hpCounter={
                imageUrl="https://steamusercontent-a.akamaihd.net/ugc/2292958473528765513/0B1849865D7DC2D609879B9D02E723B0DDE60D7F/",
            },
            stages={
                stage1={
                    cardId="39022",
                    hitPointsPerPlayer=16
                },
                stage2={
                    cardId="39023",
                    hitPointsPerPlayer=18
                },
                stage3={
                    cardId="39024",
                    hitPointsPerPlayer=25
                }
            }
        }
    },
    schemes={
        main={
            stages={
                stage1={
                    cardId="39025",
                    startingThreatPerPlayer=10,
                    targetThreatPerPlayer=25
                }
            }
        }
    },
    cards={
        wheelOfGenres={
            cardId="39026",
            position={15.75, 1.00, 29.25},
            scale=Vector(Global.getVar("CARD_SCALE_ENCOUNTER"))
        }
    },
    decks={
        encounterDeck={
            name="Mojo's Encounter Deck",
            cards={
                ["39027"]=1,
                ["39028"]=1,
                ["39029"]=2,
                ["39030"]=1,
                ["39031"]=1,
                ["39032"]=2,
                ["39033"]=2,
                ["39034"]=1
            }
        }
    },
    modularSets={
      crime = "exclude",
      fantasy = "exclude",
      horror = "exclude",
      sciFi = "exclude",
      sitcom = "exclude",
      western = "exclude"
    },
    extras={
        wheelOfGenres={
            name="Wheel of Genres",
            guid="998f2b",
            position={31.25, 0.96, 19.75},
            rotation={0, 180, 0},
            scale={3,1,3},
            locked=true
        }
    }
}

function getEncounterSetControlPanel_mojo()
  selectedScenario.mojoGenres = {
    crime = {
      name = "Crime",
      modularSetKey = "crime",
      environmentCardId = "39035",
      available = true
    },
    fantasy = {
      name = "Fantasy",
      modularSetKey = "fantasy",
      environmentCardId = "39041",
      available = true
    },
    horror = {
      name = "Horror",
      modularSetKey = "horror",
      environmentCardId = "39047",
      available = true
    },
    sciFi = {
      name = "Sci-Fi",
      modularSetKey = "sciFi",
      environmentCardId = "39053",
      available = true
    },
    sitcom = {
      name = "Sitcom",
      modularSetKey = "sitcom",
      environmentCardId = "39060",
      available = true
    },
    western = {
      name = "Western",
      modularSetKey = "western",
      environmentCardId = "39066",
      available = true
    }
  }

  for key, genre in pairs(selectedScenario.mojoGenres) do
    Global.UI.hide(genre.modularSetKey)
  end

  local guid = self.getGUID()
  local genreToggles = {}
  local genreMessage = ""
  local controlPanelHeight = ""

  if(selectedScenario.key == "magog") then
    genreMessage = "This scenario will include one of these genre encounter sets, selected randomly. Uncheck any sets that you want to exclude from this selection."
    controlPanelHeight = "70"
  elseif(selectedScenario.key == "spiral") then
    genreMessage = "This scenario will include three of these genre encounter sets, selected randomly. Uncheck any sets that you want to exclude from this selection. You can also select genre sets below to ensure that they are used."
    controlPanelHeight = "120"
  elseif(selectedScenario.key == "mojo") then
    local heroCount = getHeroCount()
    local numbers = {"two", "three", "four", "five"}
    genreMessage = "This scenario will include " .. numbers[heroCount] .. " of these genre encounter sets, selected randomly. Uncheck any sets that you want to exclude from this selection. You can also select genre sets below to ensure that they are used."
    controlPanelHeight = "120"
  end

  for key, genre in pairs(selectedScenario.mojoGenres) do
    table.insert(genreToggles, {
      tag = "Toggle",
      value = genre.name,
      attributes = {
          id = "genre_" .. genre.modularSetKey,
          onValueChanged = guid .. "/mojoToggleGenre",
          height = "15",
          width = "200",
          fontSize = "15",
          textColor = "rgba(1,1,1,1)",
          colors = "rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)|rgba(1,1,1,1)",
          isOn = true
      }
    })
  end

  local encounterSetControlPanel = {
      tag = "Panel",
      attributes = {
        preferredHeight = controlPanelHeight
      },
      children = {
          {
            tag = "VerticalLayout",
            attributes = {
              rectAlignment = "UpperLeft",
              childAlignment = "UpperLeft",
              childForceExpandHeight = "false",
              spacing = "16",
              contentSizeFitter = "vertical"
            },
            children = {
              {
                tag = "Text",
                attributes = {
                  rectAlignment = "UpperLeft",
                  alignment = "UpperLeft",
                  color = "rgba(1,1,1,1)"
                },
                value = genreMessage,
              },
              {
                tag = "HorizontalLayout",
                attributes = {
                  rectAlignment = "UpperLeft",
                  childAlignment = "UpperLeft",
                  childForceExpandWidth = "false",
                  spacing = "10"
                },
                children = genreToggles
              }
            },
          }
      }
  }

  return encounterSetControlPanel
end

function prepareScenario_mojo()
  buildGenreQueue()
  currentScenario.genreIndex = 0
end

function finalizeSetup_mojo()
  --addNextGenre()
end

function buildGenreQueue()
  local genreQueue = {}
  local genresNeeded = 0

  if(currentScenario.key == "magog") then
    genresNeeded = 1
  elseif(currentScenario.key == "spiral") then
    genresNeeded = 3
  elseif(currentScenario.key == "mojo") then
    local heroCount = getHeroCount()
    genresNeeded = heroCount + 1
  end

  for key, genre in pairs(currentScenario.mojoGenres) do
    if(genre.available) then
      table.insert(genreQueue, genre.modularSetKey)
    end
  end

  if(#genreQueue < genresNeeded) then
    local unavailableGenres = {}

    for key, genre in pairs(currentScenario.mojoGenres) do
      if(not genre.available) then
        table.insert(unavailableGenres, genre.modularSetKey)
      end
    end

    unavailableGenres = Global.call("shuffleTable", {table = unavailableGenres})

    for _, genreKey in ipairs(unavailableGenres) do
      if(#genreQueue >= genresNeeded) then
        break
      end

      table.insert(genreQueue, genreKey)
    end
  end

  genreQueue = Global.call("shuffleTable", {table = genreQueue})

  currentScenario.genreQueue = genreQueue
end

function addNextGenre()
  currentScenario.genreIndex = currentScenario.genreIndex + 1
  local heroManager = getObjectFromGUID(Global.getVar("GUID_HERO_MANAGER"))
  local heroCount = heroManager.call("getHeroCount")

  if(currentScenario.genreIndex > (heroCount + 1)) then
    broadcastToAll("There's nothing good on!", {1,1,1})
    return
  end

  if(currentScenario.genreQueue == nil) then
    log("Error: genre queue is nil.")
  end

  local genreEnvironmentCardId = currentScenario.mojoGenres[currentScenario.genreQueue[currentScenario.genreIndex]].environmentCardId
  
  Global.call("spawnCard", {
    cardId = genreEnvironmentCardId, 
    position = {20.75, 2.00, 29.75},  --TODO: create a constant (or better yet, add functionality for moving cards to a specific zone)
    scale = defaults.encounterDeck.scale,
    tags = {"group-scenario"}
  })
end

function onCardEnterZone_mojo(params)
  placeGenreSetFromEnvironment(params.zone, params.card)
end

function mojoToggleGenre(player, value, id)
  local genreKey = string.gsub(id, "genre_", "")

  for key, genre in pairs(selectedScenario.mojoGenres) do
    if(genre.modularSetKey == genreKey) then
      selectedScenario.mojoGenres[key].available = value == "True"
      break
    end
  end

  Global.UI.setAttribute(id, "isOn", value)
end

function placeGenreSetFromEnvironment(zone, card)
  local zoneDef = Global.call("getZoneDefinition", {zone = zone})

  if (not zoneDef) then return end
  if (zoneDef.zoneIndex ~= "environment") then return end

  local cardId = Global.call("getCardProperty", {card = card, property = "code"})

  local genreSetKey = ""

  for _, genre in pairs(currentScenario.mojoGenres) do
    if(genre.environmentCardId == cardId) then
      genreSetKey = genre.modularSetKey
      break
    end
  end

  if(genreSetKey == "") then return end

  for key, _ in pairs(currentScenario.modularSets) do
    if(key == genreSetKey) then
      return
    end
  end

  currentScenario.modularSets[genreSetKey] = "required"

  local encounterSetManager = getObjectFromGUID(Global.getVar("GUID_MODULAR_SET_MANAGER"))
  local newGenreSet = encounterSetManager.call("getModularSet", {modularSetKey = genreSetKey})

  newGenreSet = deepCopy(newGenreSet)

  newGenreSet.cards[cardId] = nil

  local encounterDeckPos = Vector(getEncounterDeckPosition())
  local spawnPosition = encounterDeckPos + Vector(0, 1, 0)

  Global.call("spawnDeck", {
    cards = newGenreSet.cards, 
    position = spawnPosition, 
    scale = defaults.encounterDeck.scale,
    cardTags = {"group-scenario"}
  })

  Wait.frames(function() 
    Global.call("shuffleDeck", {deckPosition = encounterDeckPos})
    broadcastToAll(newGenreSet.name.." encounter set added to encounter deck.", {1,1,1})
  end,
  30)

  saveData()
end
