scenarios["raftBreakout"] = {
    name = "Raft Breakout",
    fullyScripted = true,
    tileImageUrl = cdnUrl .. "/selectors/scenarios/selector-raft-breakout.png",
    villains = {},
    schemes = {
        main = {
            stages = {
                stage1 = {
                    cardId = "60142",
                    startingThreatPerPlayer = 2,
                    targetThreatPerPlayer = 11
                }
            }
        }
    },
    decks = {
        encounterDeck = {
            name = "Raft Breakout Encounter Deck",
            cards = {
                ["60143"] = 1,
                ["60144"] = 1,
                ["60145"] = 1,
                ["60146"] = 1,
                ["60147"] = 1,
                ["60148"] = 1,
                ["60149"] = 1,
                ["60150"] = 1
            }
        }
    },
    modularSets = {
        owl = "recommended",
        tombstone = "recommended"
    }
}

function getEncounterSetControlPanel_raftBreakout()
    return fearNoEvilGetEncounterSetPanel()
end

function prepareScenario_raftBreakout()
    fearNoEvilPrepareScenario()
end

function setUpSchemeStage_raftBreakout_main(params)
    local masterKeyCardId = "60143"
    Global.call("moveCardFromEncounterDeckById", {
        cardId = masterKeyCardId,
        searchInDiscard = true,
        zoneIndex = "attachment"
    })

    local heroManager = getObjectFromGUID(Global.getVar("GUID_HERO_MANAGER"))
    local players = heroManager.call("getPlayersInPlayerOrder")
    local playerIndex = 0

    function findRaftPrisoner()
        playerIndex = playerIndex + 1
        if (playerIndex > #players) then
            return
        end

        local zoneIndex = "minion-" .. players[playerIndex].playerColor

        Global.call("discardFromEncounterDeck", {
            searchFunction = "isPrisonerMinion",
            searchFunctionTarget = self,
            cardsToFind = 1,
            stopWhenCardsFound = true,
            zoneIndex = zoneIndex,
            callBackFunction = "findRaftPrisoner",
            callBackTarget = self
        })
    end

    findRaftPrisoner()
end

function setUpVillainStage_raftBreakout(params)
    fearNoEvilSetupVillainStage(params)
end

function isPrisonerMinion(params)
    local card = params.card
    local cardData = Global.call("getCardData", {
        card = card
    })

    local traits = cardData and cardData.traits or ""
    if (string.find(traits, "Prisoner.", 1, true)) then
        return true
    end

    return false
end
