modularSets["disasters"] = {
    name = "Disasters",
    modular = true,
    cards = {
        ["60177"] = 1,
        ["60178"] = 1,
        ["60179"] = 1,
        ["60180"] = 1,
        ["60181"] = 1
    }
}

modularSets["cops"] = {
    name = "Cops",
    modular = true,
    cards = {
        ["60182"] = 2,
        ["60183"] = 1,
        ["60184"] = 1,
        ["60185"] = 1
    }
}

modularSets["drive"] = {
    name = "Drive",
    modular = true,
    cards = {
        ["60186"] = 1,
        ["60187"] = 1,
        ["60188"] = 1,
        ["60189"] = 1,
        ["60190"] = 1
    }
}

modularSets["owl"] = {
    name = "The Owl",
    modular = true,
    cards = {
        ["60191"] = 2,
        ["60192"] = 1,
        ["60193"] = 1,
        ["60194"] = 1
    }
}

modularSets["tombstone"] = {
    name = "Tombstone",
    modular = true,
    cards = {
        ["60195"] = 1,
        ["60196"] = 1,
        ["60197"] = 1,
        ["60198"] = 1,
        ["60199"] = 1
    }
}

modularSets["tracksuitMafia"] = {
    name = "Tracksuit Mafia",
    modular = true,
    cards = {
        ["60200"] = 1,
        ["60201"] = 1,
        ["60202"] = 1,
        ["60203"] = 3,
        ["60204"] = 1
    }
}
