heroes["lukeCage"] = {
    name = "Luke Cage",
    label = "Luke Cage",
    identityCardId = "62001",
    hitPoints = 10,
    tileImageUrl = cdnUrl .. "/selectors/heroes/selector-luke-cage-temp.jpg",
    playmatImageUrl = cdnUrl .. "/playmats/playmat-luke-cage.png",
    obligationCardId = "62028",
    teams = "defenders",
    artVariant = "defender",
    decks = {
        hero = {
            ["62002"] = 1,
            ["62003"] = 2,
            ["62004"] = 1,
            ["62005"] = 2,
            ["62006"] = 2,
            ["62007"] = 1,
            ["62008"] = 1,
            ["62009"] = 2,
            ["62010"] = 2,
            ["62011"] = 1
        },
        starter = {
            ["62012"] = 1,
            ["62013"] = 1,
            ["62014"] = 1,
            ["62015"] = 3,
            ["62016"] = 1,
            ["62017"] = 2,
            ["62018"] = 3,
            ["62019"] = 3,
            ["62020"] = 1,
            ["62021"] = 1,
            ["62022"] = 3,
            ["62023"] = 1,
            ["62024"] = 1,
            ["62025"] = 1,
            ["62026"] = 1,
            ["62027"] = 1

        },
        nemesis = {
            ["62029"] = 1,
            ["62030"] = 1,
            ["62031"] = 1,
            ["62032"] = 1,
            ["62033"] = 1
        }
    }
}
